### ISSUE TITLE
Access navigator data

### ISSUE THREAD

**Issue by abuharsky** [rhysmorgan134/node-CarPlay#80]
Hi,

is it possible to access any navigator data? 
"next turn" or something?

Logging detects unknown messages with type 35, 36, etc.
Maybe it is possible to send "Enable navigator events" message?

So I really need it to re-send navigator events to the car instrument cluster.

**Comment by abuharsky** [comment]
Got it working!

With album cover and song info on instrumenr panel!


Any ideas how to get navigation data?
Maybe from app on iOS?

![IMG_4862](https://github.com/rhysmorgan134/node-CarPlay/assets/733130/e7600c9e-72b1-480e-beaf-859fce4578a9)
![IMG_4863](https://github.com/rhysmorgan134/node-CarPlay/assets/733130/9459cb31-2789-45fb-9099-89ce749ff9f4)

**Comment by igoro00** [comment]
@abuharsky Hey, did you end up getting navigation state working?

**Comment by abuharsky** [comment]
> [@abuharsky](https://github.com/abuharsky) Hey, did you end up getting navigation state working?

no, only album art,
for navigator the only way - is to catch main app screen part with navigator data, but so so

**Comment by igoro00** [comment]
too bad

I'll be trying to find out where's the program in [Carlinkit's rootfs](https://github.com/ludwig-v/wireless-carplay-dongle-reverse-engineering/discussions/219) that sends those codes over usb. I just started looking at it yesterday.

It would be great if I could somehow forward raw Android Auto (because that's what im interested in the most) [protobuf messages](https://android.googlesource.com/platform/packages/services/Car/+/master/car-lib/src/android/car/navigation/navigation_state.proto) as a custom command

EDIT: tbh this issue shouldn't have been closed. It's about navigation state and not album cover and that's clearly not done yet.

**Comment by abuharsky** [comment]
OO!
very nice!

interesting....

**Comment by rhysmorgan134** [comment]
Android auto is a lot more documented, is there a reason your are looking to use the dongle for android auto?

I don't think the dongle will ever support the navigation instructions, it's meant to be used with android headunits which wouldn't need the extra info on navigation since AA/Carplay would already be running. Sayi by that, I haven't taken a look into the latest APKs

**Comment by igoro00** [comment]
OpenAuto derivatives are dying out. Wireless AA stopped working requiring you to use [proxies](https://github.com/KreAch3R/aa-proxy-oap). I'm currently running OpenAuto Pro with that proxy and it kinda works but:
- the bandwidth is terrible:
  - You can forget about routing audio through AA because it stutters and is about 15s behind (i "solved" it by running audio through BT but it's not stable)
  - Video is like 5fps @ 480p, maybe 10. Regular controls and nav are usable but forget about panning and zooming the map.
  - If you do zoom or pan anyway you can't do it too much because the touch events stack up in the queue and once the queue overflows it crashes AA lol
  - All while the %CPU, RAM and WiFi speed sit at pretty much idle...
- OpenAutoPro requires Debian 10 which is a problem because I want to switch pulseaudio to pipewire for better BT support.
- [dash](https://github.com/openDsh/dash) solves most of the problems (slightly better performance, not on the level of node-CarPlay/react-carplay but acceptable and you can install it on Debian 12) but:
  - the UI is unusable while driving (and I dont know Qt enough to redesign it)
  - I couldn't get it to connect reliably like with OAP or the dongle.
- You can't test anything on a PC. Winter is coming in a month or two and I dont want to spend my afternoons in a freezing car outside.

In contrast node-CarPlay/react-carplay:
- lets me switch to an iPhone anytime i want (and with the way Google enshittifies Android I might do just that) 
- I'm a react developer - i can make it look how i want to easily enough and test it on my computer
- I've already designed reverse camera view with 3D animated distance sensor markers in electron. It's gonna be really easy to merge that into react-carplay compared to any of the alternatives.
- Performance, oh my god, the performance. I've started doubting if my phone is able to output the frames fast enough and as it turns out - it can. I don't even have to route audio separately!
